### ISSUE TITLE
Bok KSET

### ISSUE THREAD

**Issue by JakovGlavac** [KSET/brucifer-karte-2022#1]
Bok,
prije svega čini mi se jako cool sve kaj radite u KSET-u, pa me zanimalo postoji li način na koji bi Vam ja mogao pomoći.

Moj portfolio: https://jakovglavac.from.hr/

**Comment by pavleerg** [comment]
Hej Jakove,
Hvala ti na komentaru. Uvijek smo otvoreni za dodatno pojačanje koje nam se želi pridružiti.
Javi nam se na uclani.se@kset.org za detalje!
Bok, Pavle
